[[servers]]
  Address = "tls://iccluster098.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "ddc44c66d3200b0e247fb9255a95a2e14fa60becdd3446f7953047b7fbbabded"
  Description = "test-network-nebulaexp-6nodes-node2_medco_unlynx_server"
  [servers.Services]
