[[servers]]
  Address = "tls://iccluster096.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "2fb70ecd3347316b2c1fa130b3ef18be60daa4d3d3cc66a8bbb409c57a1d66c8"
  Description = "test-network-nebulaexp-3nodes-node0_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster097.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "b46f755195b594c6fd056036f276b00197da04801c01f32fb055f6abf606a2b1"
  Description = "test-network-nebulaexp-3nodes-node1_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster098.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "071e379405706e0cab11c4ad2509180f36859b8cfdc88c3cf68882fe266571ea"
  Description = "test-network-nebulaexp-3nodes-node2_medco_unlynx_server"
  [servers.Services]
