[[servers]]
  Address = "tls://iccluster098.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "fdef3ef758c25ffe6d9b2cf0f00b5d005b17470ee5f3005d72069c0fafc4dc43"
  Description = "test-network-nebulaexp-12nodes-node2_medco_unlynx_server"
  [servers.Services]
