version: '2.4'
services:
  glowing-bear-medco:
    extends:
      file: ../docker-compose-definitions.yml
      service: glowing-bear-medco
    environment:
      - GB_API_URL=${MEDCO_NODE_URL}/pic-sure-api-2/PICSURE
      - GB_URL=${MEDCO_NODE_URL}/glowing-bear
      - GB_OIDC_URL=${KEYCLOAK_REALM_URL}/protocol/openid-connect
      - GB_OIDC_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - GB_COTHORITY_KEY_URL=${MEDCO_NODE_URL}/cothority-key.pub.toml
      - GB_GENOMIC_ANNOTATIONS_URL=${MEDCO_NODE_URL}/genomicAnnotations
      - MEDCO_NETWORK_NAME=${MEDCO_NETWORK_NAME}
      - MEDCO_NODES_NAME=${MEDCO_NODES_NAME}

  keycloak:
    extends:
      file: ../docker-compose-definitions.yml
      service: keycloak
    environment:
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    depends_on:
      - postgresql

  picsure:
    extends:
      file: ../docker-compose-definitions.yml
      service: picsure
    environment:
      - PICSURE2_USER_ID_CLAIM=${KEYCLOAK_USER_CLAIM}
      - PICSURE2_JWKS_URL=${KEYCLOAK_REALM_URL}/protocol/openid-connect/certs
      - PICSURE2_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - MEDCO_NETWORK_NAME=${MEDCO_NETWORK_NAME}
      - MEDCO_NODES_NAME=${MEDCO_NODES_NAME}
      - MEDCO_NODES_CONNECTOR_URL=${MEDCO_NODES_CONNECTOR_URL}
    volumes:
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME}:/medco-configuration
    depends_on:
      - postgresql