[[servers]]
  Address = "tls://iccluster096.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "b46f755195b594c6fd056036f276b00197da04801c01f32fb055f6abf606a2b1"
  Description = "test-network-nebulaexp-12nodes-node0_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster097.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "071e379405706e0cab11c4ad2509180f36859b8cfdc88c3cf68882fe266571ea"
  Description = "test-network-nebulaexp-12nodes-node1_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster098.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "fdef3ef758c25ffe6d9b2cf0f00b5d005b17470ee5f3005d72069c0fafc4dc43"
  Description = "test-network-nebulaexp-12nodes-node2_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster029.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "1c839ed19563cb28633482948fbb244a8daee87f11b7f16173fd8e848c21965b"
  Description = "test-network-nebulaexp-12nodes-node3_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster033.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "8813ee7ddf54b2e3dee4ae25ad4aa2d2291a823e02adf1ff39fea686e2189426"
  Description = "test-network-nebulaexp-12nodes-node4_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster037.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "71ab26af4f5401e0937d44a6bbdbe738a9bf201d1b7dcecacc5248cba614af29"
  Description = "test-network-nebulaexp-12nodes-node5_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster129.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "7a1c1fdf6115765dad9ff4afd49ecdaaf1c16e411c2fff2734fc2be13e09d5d3"
  Description = "test-network-nebulaexp-12nodes-node6_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster054.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "87276d3d767851ba8a0ae88e2f8ee6641d0d3d48328e52f84bf4424f488a926d"
  Description = "test-network-nebulaexp-12nodes-node7_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster059.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "8c63246f7c1e87b39b239cafa93c2103f77caf7ec2ebc5d024bcc9b3ae97f36f"
  Description = "test-network-nebulaexp-12nodes-node8_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster032.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "73cdbfe96afc576140a733fcbc260101bf906caeeca094fe20f5bc36ede79868"
  Description = "test-network-nebulaexp-12nodes-node9_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster035.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "90c05b6460b296f00d3ff6f789009ad017b06b5662ef0b1407224b263649fb54"
  Description = "test-network-nebulaexp-12nodes-node10_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster041.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "907ef7f62fc41fed9132a87265e1f7cad6471f9a3e5f210607955bdf7f5e8ed4"
  Description = "test-network-nebulaexp-12nodes-node11_medco_unlynx_server"
  [servers.Services]