Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tls://iccluster096.iccluster.epfl.ch:2000"
  Secret = "mmTfA84oZHkURF0wBeu3nQRJT6sjvkFhCSwE/TbAmwo="

[[Secrets]]
  ServerID = "tls://iccluster097.iccluster.epfl.ch:2000"
  Secret = "mmTfA84oZHkURF0wBeu3nQRJT6sjvkFhCSwE/TbAmwo="

[[Secrets]]
  ServerID = "tls://iccluster098.iccluster.epfl.ch:2000"
  Secret = "mmTfA84oZHkURF0wBeu3nQRJT6sjvkFhCSwE/TbAmwo="
