[[servers]]
  Address = "tls://iccluster059.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "a0e0f65554734a3a3f288fe551d9a0e9a2aa8508bc78277b5333b6169efc2862"
  Description = "test-network-nebulaexp-9nodes-node8_medco_unlynx_server"
  [servers.Services]
