Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tls://iccluster096.iccluster.epfl.ch:2000"
  Secret = "kZfKbXNLx44DclYGXawjNIucNpMFMF3HUFma8peqwAI="

[[Secrets]]
  ServerID = "tls://iccluster097.iccluster.epfl.ch:2000"
  Secret = "kZfKbXNLx44DclYGXawjNIucNpMFMF3HUFma8peqwAI="

[[Secrets]]
  ServerID = "tls://iccluster098.iccluster.epfl.ch:2000"
  Secret = "kZfKbXNLx44DclYGXawjNIucNpMFMF3HUFma8peqwAI="

[[Secrets]]
  ServerID = "tls://iccluster029.iccluster.epfl.ch:2000"
  Secret = "kZfKbXNLx44DclYGXawjNIucNpMFMF3HUFma8peqwAI="

[[Secrets]]
  ServerID = "tls://iccluster033.iccluster.epfl.ch:2000"
  Secret = "kZfKbXNLx44DclYGXawjNIucNpMFMF3HUFma8peqwAI="

[[Secrets]]
  ServerID = "tls://iccluster037.iccluster.epfl.ch:2000"
  Secret = "kZfKbXNLx44DclYGXawjNIucNpMFMF3HUFma8peqwAI="
