[[servers]]
  Address = "tls://iccluster096.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "b46f755195b594c6fd056036f276b00197da04801c01f32fb055f6abf606a2b1"
  Description = "test-network-nebulaexp-6nodes-node0_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster097.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "071e379405706e0cab11c4ad2509180f36859b8cfdc88c3cf68882fe266571ea"
  Description = "test-network-nebulaexp-6nodes-node1_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster098.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "ddc44c66d3200b0e247fb9255a95a2e14fa60becdd3446f7953047b7fbbabded"
  Description = "test-network-nebulaexp-6nodes-node2_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster029.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "15c368590886e01bcb3f0319548d47886b6a6835bad6565b0ef7d27d82c66d0c"
  Description = "test-network-nebulaexp-6nodes-node3_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster033.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "efa4b922c5126005cfb232c4c131150da767a863f742a31cdaed5cab68e3a7e8"
  Description = "test-network-nebulaexp-6nodes-node4_medco_unlynx_server"
  [servers.Services]
[[servers]]
  Address = "tls://iccluster037.iccluster.epfl.ch:2000"
  Suite = "Ed25519"
  Public = "75f0187eb726788dac9d8185fd949a079104edc5dae16b9f79f9862388fb4a50"
  Description = "test-network-nebulaexp-6nodes-node5_medco_unlynx_server"
  [servers.Services]
